update as of 2022-03-19

diff --git a/CS236/Datalog/makefile b/CS236/Datalog/makefile
--- a/CS236/Datalog/makefile
+++ b/CS236/Datalog/makefile
@@ -1,31 +1,25 @@
 
-# makefile for project 3 pass-off tests
+# makefile for project 4 example tests
 
 NUM:=4
 
-buckets:=20 40 60 80 100
-numbers_20:=21 22 24
-numbers_40:=41 42
-numbers_60:=61 62
-numbers_80:=81 82
-numbers_100:=101 102 104 105
+numbers:=40 44 45 46 47 48 49 61 62
 
-tests:=project$(NUM)-passoff
+tests:=project$(NUM)-tests
 
-.SILENT: all $(buckets)
+.SILENT: all run
 
-all: $(buckets)
+all: run
 	@rm $(tests)/out.txt
 
-$(buckets):
-	echo "Bucket $@"; \
-	for number in ${numbers_$@} ; \
+run:
+	for number in $(numbers) ; \
 	do \
 		echo "Running input $$number" ; \
-		./lab$(NUM) $(tests)/$@/input$$number.txt > $(tests)/out.txt ; \
-		diff $(tests)/$@/answer$$number.txt $(tests)/out.txt || (echo "diff failed on test $$number \n") ; \
-	done \
+		./lab$(NUM) $(tests)/in$$number.txt > $(tests)/out.txt ; \
+		diff $(tests)/out$$number.txt $(tests)/out.txt || (echo "diff failed on test $$number \n") ; \
+	done
 
 compile:
-	g++ -Wall -Werror -std=c++17 -g *.cpp -o datalog
+	g++ -Wall -Werror -std=c++17 -g *.cpp -o lab$(NUM)
 
