update as of 2022-03-20

diff --git a/CS236/Datalog/makefile b/CS236/Datalog/makefile
--- a/CS236/Datalog/makefile
+++ b/CS236/Datalog/makefile
@@ -1,24 +1,30 @@
 
-# makefile for project 4 example tests
+# makefile for project 4 pass-off tests
 
 NUM:=4
 
-numbers:=40 44 45 46 47 48 49 61 62
+buckets:=20 40 60 80 100
+numbers_20:=21 22 23 24
+numbers_40:=41 42 44
+numbers_60:=61 62
+numbers_80:=81 82 84
+numbers_100:=101 102 103 104 105 108
 
-tests:=project$(NUM)-tests
+tests:=project$(NUM)-passoff
 
-.SILENT: all run
+.SILENT: all $(buckets)
 
-all: run
+all: $(buckets)
 	@rm $(tests)/out.txt
 
-run:
-	for number in $(numbers) ; \
+$(buckets):
+	echo "Bucket $@"; \
+	for number in ${numbers_$@} ; \
 	do \
 		echo "Running input $$number" ; \
-		./lab$(NUM) $(tests)/in$$number.txt > $(tests)/out.txt ; \
-		diff $(tests)/out$$number.txt $(tests)/out.txt || (echo "diff failed on test $$number \n") ; \
-	done
+		./lab$(NUM) $(tests)/$@/input$$number.txt > $(tests)/out.txt ; \
+		diff $(tests)/$@/answer$$number.txt $(tests)/out.txt || (echo "diff failed on test $$number \n") ; \
+	done \
 
 compile:
 	g++ -Wall -Werror -std=c++17 -g *.cpp -o lab$(NUM)
